# Generated by Django 3.0.2 on 2020-09-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_auto_20200904_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='language',
            new_name='lan',
        ),
    ]
