# Generated by Django 3.0.2 on 2020-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0003_auto_20200904_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='lan',
        ),
        migrations.AddField(
            model_name='languages',
            name='language',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
