# Generated by Django 3.0.2 on 2020-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0003_movies_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
