# Generated by Django 3.0.2 on 2020-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0004_auto_20200904_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geners', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
