# Generated by Django 3.0.2 on 2020-09-24 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0005_auto_20200924_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
