# Generated by Django 3.0.2 on 2020-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0006_movies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
