# Generated by Django 3.0.2 on 2020-09-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0008_banner_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='banner_image',
            new_name='Banner_images',
        ),
    ]
