# Generated by Django 3.0.2 on 2020-09-08 14:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0008_auto_20200908_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='parental_guidance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Language', 'Language'), ('Nudity', 'Nudity'), ('Voilence', 'Voilence')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ott.Languages'),
        ),
    ]
