# Generated by Django 3.0.2 on 2020-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0009_auto_20200924_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='comming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
